// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sync2._0.Data;

namespace Sync2._0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190303210606_ProjectTableMoreFields")]
    partial class ProjectTableMoreFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Sync2._0.Models.ProjectTable", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Json");

                    b.Property<int>("RowVersion");

                    b.Property<bool>("SyncStatus");

                    b.HasKey("Name");

                    b.ToTable("ProjectTables");
                });

            modelBuilder.Entity("Sync2._0.Models.ProjectTableChangeSet", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Json");

                    b.Property<int>("RowVersion");

                    b.Property<bool>("SyncStatus");

                    b.HasKey("Name");

                    b.ToTable("ProjectTableChangeSets");
                });
#pragma warning restore 612, 618
        }
    }
}
