// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sync2._0.Data;

namespace Sync2._0.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Sync2._0.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Sync2._0.Models.ProjectTable", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProjectId");

                    b.HasKey("Name");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTables");
                });

            modelBuilder.Entity("Sync2._0.Models.SchemaDefinition", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Columns");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ProjectTableName");

                    b.Property<int>("RowVersion");

                    b.Property<bool>("SyncStatus");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTableName");

                    b.ToTable("SchemaDefinitions");
                });

            modelBuilder.Entity("Sync2._0.Models.ProjectTable", b =>
                {
                    b.HasOne("Sync2._0.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Sync2._0.Models.SchemaDefinition", b =>
                {
                    b.HasOne("Sync2._0.Models.ProjectTable", "ProjectTable")
                        .WithMany()
                        .HasForeignKey("ProjectTableName");
                });
#pragma warning restore 612, 618
        }
    }
}
